/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package animal;

/**
 *
 * @author cta
 */
public class AnimalForm extends javax.swing.JDialog {
      private Animal animal;
    /**
     * 
     * @param parent
     * @param animal 
     */
    public AnimalForm(java.awt.Window parent, Animal animal) {
        super(parent);
        this.animal = animal;
        initComponents();
        obj2form();
        this.setVisible(true);
    }
    
    public static Animal showDialog(java.awt.Window parent, Animal animal){
        AnimalForm form= new AnimalForm(parent, animal);
        return form.animal;
    }
    
    private void obj2form(){
        cId.setText(""+animal.getId());
        cIdentificacao.setText(""+animal.getIdentificacao());
        cNascimento.setText(animal.getNascimento("dd/MM/yyyy"));
        cGenero.setSelectedIndex(animal.getGenero());
        cEspecie.setSelectedIndex(animal.getEspecie());
        cOrigem.setSelectedIndex(animal.getOrigem());
        cCategoria.setSelectedIndex(animal.getCategoria());
        cPai.setText(""+animal.getPai());
        cMae.setText(""+animal.getMae());
        cRaca.setText(""+animal.getRaca());
        cObservacao.setText(""+animal.getObservacao());
        
    }
    
    private void form2obj(){
        animal.setId(cId.getText());
        animal.setIdentificacao(cIdentificacao.getText());
        animal.setNascimento("dd/MM/yyyy", cNascimento.getText());
        animal.setGenero(cGenero.getSelectedIndex());
        animal.setEspecie(cEspecie.getSelectedIndex());
        animal.setOrigem(cOrigem.getSelectedIndex());
        animal.setCategoria(cCategoria.getSelectedIndex());
        animal.setPai(cPai.getText());
        animal.setMae(cMae.getText());
        animal.setObservacao(cObservacao.getText());
        
    }
     
    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        this.animal = null;
        this.setVisible(false);
    }                                         

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {                                    
       form2obj();
       this.setVisible(false);
    }                                   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cId = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cIdentificacao = new javax.swing.JTextField();
        cNascimento = new javax.swing.JTextField();
        cGenero = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        cOrigem = new javax.swing.JComboBox();
        cEspecie = new javax.swing.JComboBox();
        cRaca = new javax.swing.JTextField();
        cCategoria = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        cPai = new javax.swing.JTextField();
        cMae = new javax.swing.JTextField();
        sObservacao = new javax.swing.JScrollPane();
        cObservacao = new javax.swing.JEditorPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bCancelar = new javax.swing.JButton();
        bOk = new javax.swing.JButton();

        cId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));

        setTitle("Animais");
        setPreferredSize(new java.awt.Dimension(900, 600));

        jPanel5.setLayout(new java.awt.GridLayout(2, 0));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        cIdentificacao.setBorder(javax.swing.BorderFactory.createTitledBorder("N° de Indentificação"));
        jPanel3.add(cIdentificacao);

        cNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nascimento"));
        jPanel3.add(cNascimento);

        cGenero.setBorder(javax.swing.BorderFactory.createTitledBorder("Genero"));
        jPanel3.add(cGenero);

        jPanel5.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        cOrigem.setBorder(javax.swing.BorderFactory.createTitledBorder("Origem"));
        jPanel4.add(cOrigem);

        cEspecie.setBorder(javax.swing.BorderFactory.createTitledBorder("Especie"));
        jPanel4.add(cEspecie);

        cRaca.setBorder(javax.swing.BorderFactory.createTitledBorder("Raça"));
        jPanel4.add(cRaca);

        cCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        jPanel4.add(cCategoria);

        jPanel5.add(jPanel4);

        getContentPane().add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 701));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        cPai.setBorder(javax.swing.BorderFactory.createTitledBorder("Pai"));
        jPanel7.add(cPai);

        cMae.setBorder(javax.swing.BorderFactory.createTitledBorder("Mãe"));
        jPanel7.add(cMae);

        jPanel6.add(jPanel7, java.awt.BorderLayout.NORTH);

        sObservacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Observação"));
        sObservacao.setViewportView(cObservacao);

        jPanel6.add(sObservacao, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconemissao.png"))); // NOI18N
        jPanel8.add(jLabel1);

        jPanel1.add(jPanel8);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bCancelar.setMnemonic('C');
        bCancelar.setText("Cancelar");
        bCancelar.setToolTipText("");
        jPanel2.add(bCancelar);

        bOk.setMnemonic('O');
        bOk.setText("OK");
        jPanel2.add(bOk);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(811, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cCategoria;
    private javax.swing.JComboBox cEspecie;
    private javax.swing.JComboBox cGenero;
    private javax.swing.JTextField cId;
    private javax.swing.JTextField cIdentificacao;
    private javax.swing.JTextField cMae;
    private javax.swing.JTextField cNascimento;
    private javax.swing.JEditorPane cObservacao;
    private javax.swing.JComboBox cOrigem;
    private javax.swing.JTextField cPai;
    private javax.swing.JTextField cRaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane sObservacao;
    // End of variables declaration//GEN-END:variables
}
