package insumosAgri;

/**
 *
 * @author cta
 */
public class InsumoForm extends javax.swing.JDialog {

    private Insumo insumo;
    
    /**
     * Creates new form InsumoTab
     * @param parent
     * @param insumo
     */
    public InsumoForm(java.awt.Window parent, Insumo insumo) {
        super(parent);
        this.insumo = insumo;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    public static Insumo showDialog(java.awt.Window parent, Insumo insumo) {
        InsumoForm form = new InsumoForm(parent, insumo);
        return form.insumo;
    }

    private void obj2form() {
        tId.setText(""+insumo.getId());
        tNome.setText(insumo.getNome());
        tValor.setText(insumo.getValor("#,##0.00"));
        cCategoria.setSelectedIndex(insumo.getCategoria());
        cUnidade.setSelectedIndex(insumo.getUnidade());
        tQuantidade.setText(insumo.getQuantidade("#,##0.###"));
    }
    
    private void form2obj() {
        insumo.setId(tId.getText());
        insumo.setNome(tNome.getText());
        insumo.setValor(insumo.getValor());
        insumo.setCategoria(cCategoria.getSelectedIndex());
        insumo.setUnidade(cUnidade.getSelectedIndex());
        insumo.setQuantidade(insumo.getQuantidade());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tId = new javax.swing.JFormattedTextField();
        pDados = new javax.swing.JPanel();
        cCategoria = new javax.swing.JComboBox(Insumo.CATEGORIA);
        tNome = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        cUnidade = new javax.swing.JComboBox(Insumo.UNIDADE);
        tQuantidade = new javax.swing.JFormattedTextField();
        tValor = new javax.swing.JFormattedTextField();
        pBotoes = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        tId.setFocusable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pDados.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        cCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        pDados.add(cCategoria);

        tNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        pDados.add(tNome);

        jPanel1.setLayout(new java.awt.GridLayout());

        cUnidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidade"));
        jPanel1.add(cUnidade);

        tQuantidade.setEditable(false);
        tQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        jPanel1.add(tQuantidade);
        tQuantidade.getAccessibleContext().setAccessibleName("tQuantidade");

        tValor.setEditable(false);
        tValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor"));
        jPanel1.add(tValor);
        tValor.getAccessibleContext().setAccessibleName("tValor");

        pDados.add(jPanel1);

        getContentPane().add(pDados, java.awt.BorderLayout.CENTER);

        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pBotoes.add(bOk);

        bCancelar.setMnemonic('C');
        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        pBotoes.add(bCancelar);

        getContentPane().add(pBotoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(509, 243));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        form2obj();
        this.setVisible(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.insumo = null;
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cCategoria;
    private javax.swing.JComboBox cUnidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pDados;
    private javax.swing.JFormattedTextField tId;
    private javax.swing.JFormattedTextField tNome;
    private javax.swing.JFormattedTextField tQuantidade;
    private javax.swing.JFormattedTextField tValor;
    // End of variables declaration//GEN-END:variables
}
