/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package maquina;

/**
 *
 * @author cta17
 */
public class MaquinaForm extends javax.swing.JDialog {

    private Maquina maquina; 
    
    public MaquinaForm(java.awt.Window parent, Maquina maquina) {
        super(parent);
        this.maquina = maquina;
        initComponents();
        obj2form();
        this.setVisible(true);
    }
    
     public static Maquina showDialog(java.awt.Window parent, Maquina maquina){
        MaquinaForm form = new MaquinaForm(parent, maquina);
        return form.maquina;
    }
     
     private void obj2form(){
         tId.setText(""+maquina.getId());
         tMaquina.setText(""+maquina.getMaquina());
         tDescricao.setText(""+maquina.getDescricao());
         tVidaUtil.setText(""+maquina.getVidaUtil());
         tCompra.setText(""+maquina.getDataCompra());
         tValorCompra.setText(""+maquina.getValorCompra());
         tAbrigo.setText(""+maquina.getAbrigo());
         tManutencao.setText(""+maquina.getAbrigo());
         tLubrificacao.setText(""+maquina.getLubrificacao());
     }
     
     private void form2obj(){
         maquina.setId(tId.getText());
         maquina.setMaquina(tMaquina.getText());
         maquina.setDescricao(tDescricao.getText());
         maquina.setVidaUtil(tVidaUtil.getText());
         maquina.setDataCompra("dd/MM/yyyy", tDataCompra.getText());
         
     }
    
    /**
     * Creates new form MaquinaForm
     */
    public MaquinaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tId = new javax.swing.JTextField();
        jInformacoes = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tMaquina = new javax.swing.JTextField();
        tDescricao = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        tVidaUtil = new javax.swing.JTextField();
        tCompra = new javax.swing.JFormattedTextField();
        tValorCompra = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        tAbrigo = new javax.swing.JTextField();
        tManutencao = new javax.swing.JTextField();
        tLubrificacao = new javax.swing.JTextField();
        jBotao = new javax.swing.JPanel();
        tDataCompra = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));

        jInformacoes.setLayout(new java.awt.GridLayout(3, 3));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        tMaquina.setBorder(javax.swing.BorderFactory.createTitledBorder("Máquina"));
        jPanel1.add(tMaquina);

        tDescricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        jPanel1.add(tDescricao);

        jInformacoes.add(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3));

        tVidaUtil.setBorder(javax.swing.BorderFactory.createTitledBorder("Vida Útil (horas)"));
        jPanel2.add(tVidaUtil);

        tCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Compra"));
        try {
            tCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(tCompra);

        tValorCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Compra R$"));
        jPanel2.add(tValorCompra);

        jInformacoes.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(1, 3));

        tAbrigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Abrigo %"));
        jPanel3.add(tAbrigo);

        tManutencao.setBorder(javax.swing.BorderFactory.createTitledBorder("Manutenção %"));
        jPanel3.add(tManutencao);

        tLubrificacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Lubrificação %"));
        jPanel3.add(tLubrificacao);

        jInformacoes.add(jPanel3);

        getContentPane().add(jInformacoes, java.awt.BorderLayout.CENTER);

        tDataCompra.setText("Ok");
        tDataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDataCompraActionPerformed(evt);
            }
        });
        jBotao.add(tDataCompra);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jBotao.add(bCancelar);

        getContentPane().add(jBotao, java.awt.BorderLayout.SOUTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tDataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDataCompraActionPerformed
        form2obj();
        this.setVisible(false);
    }//GEN-LAST:event_tDataCompraActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.maquina= null;
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JPanel jBotao;
    private javax.swing.JPanel jInformacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField tAbrigo;
    private javax.swing.JFormattedTextField tCompra;
    private javax.swing.JButton tDataCompra;
    private javax.swing.JTextField tDescricao;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tLubrificacao;
    private javax.swing.JTextField tManutencao;
    private javax.swing.JTextField tMaquina;
    private javax.swing.JTextField tValorCompra;
    private javax.swing.JTextField tVidaUtil;
    // End of variables declaration//GEN-END:variables
}
