/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funcionario;

/**
 *
 * @author cta
 */
public class FuncionarioForm extends javax.swing.JDialog {
    private Funcionario funcionario;
    /**
     * Creates new form FuncionarioForm
     */
    public FuncionarioForm(java.awt.Window parent, Funcionario funcionario) {
        super(parent);
        this.funcionario = funcionario;
        initComponents();
        obj2form();
        this.setVisible(true);

    }

    public static Funcionario showDialog(java.awt.Window parent, Funcionario funcionario) {
        FuncionarioForm form = new FuncionarioForm(parent, funcionario);
        return form.funcionario;

    }

    private void obj2form() {
        tId.setText("" + funcionario.getId());
        tNome.setText(funcionario.getNome());
        tNascimento.setText(funcionario.getNascimento("dd/MM/yyyy"));
        cGenero.setSelectedIndex(funcionario.getGenero());
        tCpf.setText(funcionario.getCpf());
        cCargo.setSelectedIndex(funcionario.getCargo());
        cContrato.setSelectedIndex(funcionario.getContrato());
        tEncargos.setText(funcionario.getEncargos("#,##0.###"));
        tSalario.setText(funcionario.getSalario("#,##0.00"));
        tUsuario.setText(funcionario.getUsuario());
        tSenha.setText(funcionario.getSenha());
    }

    private void form2obj() {
        funcionario.setId(tId.getText());
        funcionario.setNome(tNome.getText());
        funcionario.setNascimento("dd/MM/yyyy", tNascimento.getText());
        funcionario.setGenero(cGenero.getSelectedIndex());
        funcionario.setCargo(cCargo.getSelectedIndex());
        funcionario.setContrato(cContrato.getSelectedIndex());
        funcionario.setCpf(tCpf.getText());
        funcionario.setEncargos("",tEncargos.getText());
        funcionario.setSalario("",tSalario.getText());
        funcionario.setUsuario(tUsuario.getText());
        funcionario.setSenha(tSenha.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tId = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        tNome = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        tNascimento = new javax.swing.JFormattedTextField();
        tCpf = new javax.swing.JFormattedTextField();
        cGenero = new javax.swing.JComboBox(Funcionario.GENERO);
        jPanel4 = new javax.swing.JPanel();
        cCargo = new javax.swing.JComboBox(Funcionario.CARGO);
        cContrato = new javax.swing.JComboBox(Funcionario.CONTRATO);
        jPanel5 = new javax.swing.JPanel();
        tSalario = new javax.swing.JFormattedTextField();
        tEncargos = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        tUsuario = new javax.swing.JFormattedTextField();
        tSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        tNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        jPanel1.add(tNome);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        tNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nascimento"));
        try {
            tNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(tNascimento);

        tCpf.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        try {
            tCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(tCpf);

        cGenero.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));
        jPanel3.add(cGenero);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        cCargo.setBorder(javax.swing.BorderFactory.createTitledBorder("Cargo"));
        jPanel4.add(cCargo);

        cContrato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contrato"));
        jPanel4.add(cContrato);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        tSalario.setBorder(javax.swing.BorderFactory.createTitledBorder("Salário R$"));
        tSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jPanel5.add(tSalario);

        tEncargos.setBorder(javax.swing.BorderFactory.createTitledBorder("Encargo %"));
        tEncargos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));
        jPanel5.add(tEncargos);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        tUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));
        jPanel6.add(tUsuario);

        tSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        jPanel6.add(tSenha);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        jPanel2.add(bOk);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(bCancelar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(657, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        form2obj();
        this.setVisible(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.funcionario = null;
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cCargo;
    private javax.swing.JComboBox cContrato;
    private javax.swing.JComboBox cGenero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JFormattedTextField tCpf;
    private javax.swing.JFormattedTextField tEncargos;
    private javax.swing.JFormattedTextField tId;
    private javax.swing.JFormattedTextField tNascimento;
    private javax.swing.JFormattedTextField tNome;
    private javax.swing.JFormattedTextField tSalario;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JFormattedTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
