/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ctalab
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDados = new javax.swing.JPanel();
        tPeso = new javax.swing.JFormattedTextField();
        tAltura = new javax.swing.JFormattedTextField();
        lIMC = new javax.swing.JLabel();
        lClassificacao = new javax.swing.JLabel();
        pBotoes = new javax.swing.JPanel();
        bCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculo de IMC");

        pDados.setLayout(new java.awt.GridLayout(2, 2));

        tPeso.setBorder(javax.swing.BorderFactory.createTitledBorder("Peso em Kg"));
        pDados.add(tPeso);

        tAltura.setBorder(javax.swing.BorderFactory.createTitledBorder("Altura em m"));
        pDados.add(tAltura);

        lIMC.setBorder(javax.swing.BorderFactory.createTitledBorder("IMC"));
        pDados.add(lIMC);

        lClassificacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Classificação"));
        pDados.add(lClassificacao);

        getContentPane().add(pDados, java.awt.BorderLayout.CENTER);

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });
        pBotoes.add(bCalcular);

        getContentPane().add(pBotoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
// Declaraçao de objeto IMC
        imc.IMC i;
        // Instancia o objeto
        i = new imc.IMC();
        //Definiçaodos valores objetos
        i.setPesoF(tPeso.getText());
        i.setAlturaF(tAltura.getText());
        // Obtem os valores calculados
        lIMC.setText(i.getIMC_F());
        lClassificacao.setText(i.getClassificacao());
     
    }//GEN-LAST:event_bCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCalcular;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lIMC;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pDados;
    private javax.swing.JFormattedTextField tAltura;
    private javax.swing.JFormattedTextField tPeso;
    // End of variables declaration//GEN-END:variables
}
