/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;

/**
 *
 * @author cta
 */
public class ClienteTab extends javax.swing.JDialog {

    private final Session session;
    private final List<Cliente> lista;

    /**
     * Creates new form ClienteTab
     *
     * @param parent
     */
    public ClienteTab(java.awt.Window parent, Session session) {
        super(parent);
        this.session = session;
        this.lista = new ArrayList<>();
        initComponents();
        refresh();
        this.setVisible(true);
    }
public static void showDialog(java.awt.Window parent, Session session){
    new ClienteTab(parent, session);
}
    /**
     * Atualiza a tabela
     */
    private void refresh() {
        ///limpa a lista
        lista.removeAll(lista);
        //Obtem uma lista de clientes do banco de dados
        lista.addAll(ClienteDAO.loadList(session));

        DefaultTableModel mTabela = (DefaultTableModel) tTabela.getModel();
        while (mTabela.getRowCount() > 0) {
            mTabela.removeRow(0);

        }
        for (Cliente c : lista) {
            List linha = new ArrayList();
            linha.add(c.getId());
            linha.add(c.getNome());
            linha.add(c.getNascimento("dd/MM/yyyy"));
            linha.add(c.getCpf());
            mTabela.addRow(linha.toArray());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTabela = new javax.swing.JPanel();
        sTabela = new javax.swing.JScrollPane();
        tTabela = new javax.swing.JTable();
        pBotoes = new javax.swing.JPanel();
        bInserir = new javax.swing.JButton();
        bEditar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pTabela.setLayout(new java.awt.BorderLayout());

        tTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Nascimento", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sTabela.setViewportView(tTabela);

        pTabela.add(sTabela, java.awt.BorderLayout.CENTER);

        getContentPane().add(pTabela, java.awt.BorderLayout.CENTER);

        bInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock_new-16.png"))); // NOI18N
        bInserir.setMnemonic('I');
        bInserir.setText("Inserir");
        bInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInserirActionPerformed(evt);
            }
        });
        pBotoes.add(bInserir);

        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock_open-16.png"))); // NOI18N
        bEditar.setMnemonic('E');
        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });
        pBotoes.add(bEditar);

        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock_calc-cancel-16.png"))); // NOI18N
        bExcluir.setMnemonic('E');
        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });
        pBotoes.add(bExcluir);

        getContentPane().add(pBotoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(410, 330));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInserirActionPerformed
        Cliente c = new Cliente();
        c = ClienteForm.showDialog(this, c);
        if (c!= null) {
            ClienteDAO.save(session, c);
            refresh();
        }
    }//GEN-LAST:event_bInserirActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        Cliente c = lista.get(tTabela.getSelectedRow());
        c = ClienteForm.showDialog(this, c);
        if (c != null) {
            ClienteDAO.save(session, c);
            refresh();
        }
    }//GEN-LAST:event_bEditarActionPerformed

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
        Cliente c = lista.get(tTabela.getSelectedRow());
        Integer resposta = JOptionPane.showConfirmDialog(this, "Deseja excluir o cliente " + c.getNome() + "?");
        if (resposta == JOptionPane.YES_OPTION) {
            ClienteDAO.delete(session, c);
            refresh();
        }
    }//GEN-LAST:event_bExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bInserir;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pTabela;
    private javax.swing.JScrollPane sTabela;
    private javax.swing.JTable tTabela;
    // End of variables declaration//GEN-END:variables
}
