package cliente;

/**
 *
 * @author cta
 */
public class ClienteForm extends javax.swing.JDialog {

    private  Cliente cliente;
    
    /**
     * Creates new form ClienteTab
     * @param parent
     * @param cliente
     */
    public ClienteForm(java.awt.Window parent, Cliente cliente) {
        super(parent);
        this.cliente = cliente;
        initComponents();
        obj2form();
        this.setVisible(true);
    }
    public static Cliente showDialog(java.awt.Window parent, Cliente cliente){
        ClienteForm form = new ClienteForm(parent, cliente);
        return form.cliente;
    }
    
    private void obj2form(){
        tId.setText(""+cliente.getId());
        tNome.setText(cliente.getNome());
        tNascimento.setText(cliente.getNascimento("dd/MM/yyyy"));
        cGenero.setSelectedIndex(cliente.getGenero());
        tCpf.setText(cliente.getCpf());
        tUsuario.setText(cliente.getUsuario());
        tSenha.setText(cliente.getSenha());
    }
    
    private void form2obj() {
        cliente.setId(tId.getText());
        cliente.setNome(tNome.getText());
        cliente.setNascimento("dd/MM/yyyy",tNascimento.getText());
        cliente.setGenero(cGenero.getSelectedIndex());
        cliente.setCpf(tCpf.getText());
        cliente.setUsuario(tUsuario.getText());
        cliente.setSenha(tSenha.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pDados = new javax.swing.JPanel();
        tId = new javax.swing.JFormattedTextField();
        tNome = new javax.swing.JFormattedTextField();
        tNascimento = new javax.swing.JFormattedTextField();
        cGenero = new javax.swing.JComboBox();
        tCpf = new javax.swing.JFormattedTextField();
        tUsuario = new javax.swing.JFormattedTextField();
        tSenha = new javax.swing.JPasswordField();
        pBotoes = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);

        pDados.setLayout(new java.awt.GridLayout(7, 0, 10, 10));

        tId.setEditable(false);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("ID")));
        tId.setFocusable(false);
        pDados.add(tId);

        tNome.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
        pDados.add(tNome);

        tNascimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Nascimento"));
        try {
            tNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(tNascimento);

        cGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecione-", "Masculino", "Feminino" }));
        cGenero.setBorder(javax.swing.BorderFactory.createTitledBorder("Gênero"));
        pDados.add(cGenero);

        tCpf.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));
        try {
            tCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pDados.add(tCpf);

        tUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário"));
        pDados.add(tUsuario);

        tSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Senha"));
        pDados.add(tSenha);

        getContentPane().add(pDados, java.awt.BorderLayout.CENTER);

        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pBotoes.add(bOk);

        bCancelar.setText("Cancelar");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        pBotoes.add(bCancelar);

        getContentPane().add(pBotoes, java.awt.BorderLayout.SOUTH);

        setSize(new java.awt.Dimension(518, 473));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
       form2obj();
        setVisible(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.cliente = null;
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cGenero;
    private javax.swing.JPanel pBotoes;
    private javax.swing.JPanel pDados;
    private javax.swing.JFormattedTextField tCpf;
    private javax.swing.JFormattedTextField tId;
    private javax.swing.JFormattedTextField tNascimento;
    private javax.swing.JFormattedTextField tNome;
    private javax.swing.JPasswordField tSenha;
    private javax.swing.JFormattedTextField tUsuario;
    // End of variables declaration//GEN-END:variables
}
