package main;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

/**
 *
 * @author cta
 */
public class Main extends javax.swing.JFrame {

    
     private SessionFactory createSessionFactory(){
        Configuration config = new Configuration();
        config.setProperty("hibernate.connection.driver", "org.apache.derby.jdbc.EmbeddedDriver");
        config.setProperty("hibernate.connection.url","jdbc:derby:./data;territory=pt_BR;create=TRUE");
        config.setProperty("hibernate.connection.dialect","org.hibernate.dialect.DerbyTenFiveDialect");
        config.setProperty("hibernate.hbm2ddl.auto","update");
        config.addAnnotatedClass(maquina.Maquina.class);
        config.addAnnotatedClass(animal.Animal.class);
        config.addAnnotatedClass(area.Area.class);
        config.addAnnotatedClass(insumosAgri.Insumo.class);
        config.addAnnotatedClass(funcionario.Funcionario.class);
        config.addAnnotatedClass(caixa.Caixa.class);
        return config.buildSessionFactory();
        
    }
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        factory = createSessionFactory();
    }

    private final SessionFactory factory;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mFuncionarios = new javax.swing.JMenuItem();
        mArea = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenuItem();
        mCaixa = new javax.swing.JMenuItem();
        mMaquinas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jMenu1.setText("Arquivo");

        mFuncionarios.setText("Funcionários");
        mFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFuncionariosActionPerformed(evt);
            }
        });
        jMenu1.add(mFuncionarios);

        mArea.setText("Áreas");
        mArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAreaActionPerformed(evt);
            }
        });
        jMenu1.add(mArea);

        mAnimais.setText("Animais");
        mAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAnimaisActionPerformed(evt);
            }
        });
        jMenu1.add(mAnimais);

        mCaixa.setText("Caixa");
        mCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCaixaActionPerformed(evt);
            }
        });
        jMenu1.add(mCaixa);

        mMaquinas.setText("Maquinas");
        mMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMaquinasActionPerformed(evt);
            }
        });
        jMenu1.add(mMaquinas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(697, 431));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMaquinasActionPerformed
         //obtem uma sessão de fabrica de sessoes
        Session session = factory.openSession();
        //abre a sessao para transação com bd
        session.beginTransaction();
        //abre a tabela de maquina
        maquina.MaquinaTab.showDialog(this, session);
    }//GEN-LAST:event_mMaquinasActionPerformed

    private void mCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCaixaActionPerformed
         //obtem uma sessão de fabrica de sessoes
        Session session = factory.openSession();
        //abre a sessao para transação com bd
        session.beginTransaction();
        //abre a tabela de maquina
        caixa.CaixaTab.showDialog(this, session);
    }//GEN-LAST:event_mCaixaActionPerformed

    private void mAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAnimaisActionPerformed
        //obtem uma sessão de fabrica de sessoes
        Session session = factory.openSession();
        //abre a sessao para transação com bd
        session.beginTransaction();
        //abre a tabela de maquina
        animal.AnimalTab.showDialog(this, session);
    }//GEN-LAST:event_mAnimaisActionPerformed

    private void mAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAreaActionPerformed
         //obtem uma sessão de fabrica de sessoes
        Session session = factory.openSession();
        //abre a sessao para transação com bd
        session.beginTransaction();
        //abre a tabela de maquina
        area.AreaTab.showDialog(this, session);
    }//GEN-LAST:event_mAreaActionPerformed

    private void mFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFuncionariosActionPerformed
         //obtem uma sessão de fabrica de sessoes
        Session session = factory.openSession();
        //abre a sessao para transação com bd
        session.beginTransaction();
        //abre a tabela de maquina
        funcionario.FuncionarioTab.showDialog(this, session);
    }//GEN-LAST:event_mFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
                                       
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mAnimais;
    private javax.swing.JMenuItem mArea;
    private javax.swing.JMenuItem mCaixa;
    private javax.swing.JMenuItem mFuncionarios;
    private javax.swing.JMenuItem mMaquinas;
    // End of variables declaration//GEN-END:variables
}
