package venda.vendaitem;
/**
 *
 * @author JSQLGen
 */
public class VendaItemForm extends javax.swing.JDialog {
    private final java.sql.Connection connection;
    private VendaItem vendaItem;

    /** Construtor do form VendaItemForm
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param vendaItem Objeto a ser editado
     */
    public VendaItemForm(java.awt.Window parent, java.sql.Connection connection, VendaItem vendaItem) {
        super(parent);
        this.connection = connection;
        this.vendaItem = vendaItem;
        initComponents();
        obj2form();
        this.setVisible(true);
    }

    /** Exibe caixa de diálogo para preenchimento dos campos
     * @param parent Janela mãe
     * @param connection Conexão com o BD
     * @param vendaItem Objeto a ser editado
     * @return the vendaItem
     */
    public static VendaItem showInputDialog(java.awt.Window parent, java.sql.Connection connection, VendaItem vendaItem) {
        return new VendaItemForm(parent, connection, vendaItem).vendaItem;
    }

    /** Transfere os dados do objeto para o formulário */
    private void obj2form() {
        tId.setText(vendaItem.getId()==null?"":vendaItem.getId().toString());
        cProduto.setSelectedItem(vendaItem.getProduto().getNome());
        tQuantidade.setText(""+vendaItem.getQuantidade());
        tValor.setText(vendaItem.getValorF());
    }

    /** Transfere os dados do formulário para o objeto */
    private void form2obj() {
        vendaItem.setId(tId.getText());
        try{
            vendaItem.setProduto(produto.ProdutoDAO.loadByNome(connection, cProduto.getSelectedItem().toString()));
        } catch(java.sql.SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Falha na leitura do banco de dados!\n"+e.getMessage(),"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        vendaItem.setQuantidade(tQuantidade.getText());
        vendaItem.setValorF(tValor.getText());
    }

    /** valida os dados do formulário */
    private String validateForm() {
        String fieldError ="";
        if(cProduto.getSelectedItem()==null) fieldError +="Produto\n";
        if(Integer.parseInt(tQuantidade.getText())<0) fieldError +="Quantidade\n";
        if(new java.text.DecimalFormat("#,##0.00").parse(tValor.getText(),new java.text.ParsePosition(0)).floatValue()<0) fieldError +="Valor\n";
        return fieldError;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pData = new javax.swing.JPanel();
        tbData = new javax.swing.JTabbedPane();
        pButtons = new javax.swing.JPanel();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        tId = new javax.swing.JLabel();
        cProduto = new javax.swing.JComboBox(produto.ProdutoDAO.loadNomeList(connection).toArray());
        tQuantidade = new javax.swing.JFormattedTextField();
        tValor = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de VendaItem");
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pData.setLayout(new java.awt.GridLayout(5, 0));
        tId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        tId.setBorder(javax.swing.BorderFactory.createTitledBorder("Id"));
        pData.add(tId);
        cProduto.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));
        pData.add(cProduto);
        tQuantidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        tQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tQuantidade.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pData.add(tQuantidade);
        tValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor"));
        tValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        tValor.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        pData.add(tValor);
        getContentPane().add(pData, java.awt.BorderLayout.NORTH);
        getContentPane().add(tbData, java.awt.BorderLayout.CENTER);
        pButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
        bOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-accept-16.png"))); // NOI18N
        bOk.setMnemonic('O');
        bOk.setText("Ok");
        bOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOkActionPerformed(evt);
            }
        });
        pButtons.add(bOk);
        bCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbox/images/stock_calc-cancel-16.png"))); // NOI18N
        bCancel.setMnemonic('C');
        bCancel.setText("Cancelar");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        pButtons.add(bCancel);
        getContentPane().add(pButtons, java.awt.BorderLayout.SOUTH);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        String fieldError =validateForm();
        if(fieldError.length()==0) {
            form2obj();
            this.setVisible(false);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Verifique os campos seguintes e tente novamente!\n"+fieldError,"Aviso",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        vendaItem = null;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_bCancelActionPerformed


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        bCancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pData;
    private javax.swing.JTabbedPane tbData;
    private javax.swing.JLabel tId;
    private javax.swing.JComboBox cProduto;
    private javax.swing.JFormattedTextField tQuantidade;
    private javax.swing.JFormattedTextField tValor;
    // End of variables declaration//GEN-END:variables
}
