/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MCristina
 */
public class Quebracabeca extends javax.swing.JFrame {

    Integer movimentos;

    /**
     * Creates new form Quebracabeca
     */
    public Quebracabeca() {
        movimentos = 0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b11 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lMovimento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel1.add(b11);

        b21.setText("15");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });
        jPanel1.add(b21);

        b31.setText("14");
        b31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b31ActionPerformed(evt);
            }
        });
        jPanel1.add(b31);

        b41.setText("13");
        b41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b41ActionPerformed(evt);
            }
        });
        jPanel1.add(b41);

        b12.setText("12");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel1.add(b12);

        b22.setText("11");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        jPanel1.add(b22);

        b32.setText("10");
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        jPanel1.add(b32);

        b42.setText("9");
        b42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b42ActionPerformed(evt);
            }
        });
        jPanel1.add(b42);

        b13.setText("8");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel1.add(b13);

        b23.setText("7");
        b23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b23ActionPerformed(evt);
            }
        });
        jPanel1.add(b23);

        b33.setText("6");
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });
        jPanel1.add(b33);

        b43.setText("5");
        b43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b43ActionPerformed(evt);
            }
        });
        jPanel1.add(b43);

        b14.setText("4");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel1.add(b14);

        b24.setText("3");
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });
        jPanel1.add(b24);

        b34.setText("2");
        b34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b34ActionPerformed(evt);
            }
        });
        jPanel1.add(b34);

        b44.setText("1");
        b44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b44ActionPerformed(evt);
            }
        });
        jPanel1.add(b44);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        lMovimento.setText("jLabel1");
        jPanel2.add(lMovimento);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        setSize(new java.awt.Dimension(466, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed

        //verifica abaixo
        if (b12.getText().isEmpty()) {
            b12.setText(b11.getText());
            b11.setText("");
            movimentos++;
        }
        //verifica direia
        if (b21.getText().isEmpty()) {
            b21.setText(b11.getText());
            b11.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);
    }//GEN-LAST:event_b11ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed

        //verifica abaixo
        if (b22.getText().isEmpty()) {
            b22.setText(b21.getText());
            b21.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b11.getText().isEmpty()) {
            b11.setText(b21.getText());
            b21.setText("");
            movimentos++;
        }
        //verifica direia
        if (b31.getText().isEmpty()) {
            b31.setText(b21.getText());
            b21.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);
    }//GEN-LAST:event_b21ActionPerformed

    private void b31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b31ActionPerformed
        //verifica abaixo
        if (b32.getText().isEmpty()) {
            b32.setText(b31.getText());
            b31.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b21.getText().isEmpty()) {
            b21.setText(b31.getText());
            b31.setText("");
            movimentos++;
        }
        //verifica direia
        if (b41.getText().isEmpty()) {
            b41.setText(b31.getText());
            b31.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);
    }//GEN-LAST:event_b31ActionPerformed

    private void b41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b41ActionPerformed

        //verifica abaixo
        if (b42.getText().isEmpty()) {
            b42.setText(b41.getText());
            b41.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b31.getText().isEmpty()) {
            b31.setText(b41.getText());
            b41.setText("");
            movimentos++;
        }

        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b41ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        //verifica acima
        if (b11.getText().isEmpty()) {
            b11.setText(b12.getText());
            b12.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b13.getText().isEmpty()) {
            b13.setText(b12.getText());
            b12.setText("");
            movimentos++;
        }
        //verifica direia
        if (b22.getText().isEmpty()) {
            b22.setText(b12.getText());
            b12.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b12ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        //verifica acima
        if (b21.getText().isEmpty()) {
            b21.setText(b22.getText());
            b22.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b23.getText().isEmpty()) {
            b23.setText(b22.getText());
            b22.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b12.getText().isEmpty()) {
            b12.setText(b22.getText());
            b22.setText("");
            movimentos++;
        }
        //verifica direia
        if (b32.getText().isEmpty()) {
            b32.setText(b22.getText());
            b22.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);
    }//GEN-LAST:event_b22ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
//verifica acima
        if (b31.getText().isEmpty()) {
            b31.setText(b32.getText());
            b32.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b33.getText().isEmpty()) {
            b33.setText(b32.getText());
            b32.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b22.getText().isEmpty()) {
            b22.setText(b32.getText());
            b32.setText("");
            movimentos++;
        }
        //verifica direia
        if (b42.getText().isEmpty()) {
            b42.setText(b32.getText());
            b32.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);
     }//GEN-LAST:event_b32ActionPerformed

    private void b42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b42ActionPerformed
        //verifica acima
        if (b41.getText().isEmpty()) {
            b41.setText(b42.getText());
            b42.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b43.getText().isEmpty()) {
            b43.setText(b42.getText());
            b42.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b32.getText().isEmpty()) {
            b32.setText(b42.getText());
            b42.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b42ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        //verifica acima
        if (b12.getText().isEmpty()) {
            b12.setText(b13.getText());
            b13.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b14.getText().isEmpty()) {
            b14.setText(b13.getText());
            b13.setText("");
            movimentos++;

        }
        //verifica direia
        if (b23.getText().isEmpty()) {
            b23.setText(b13.getText());
            b13.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b13ActionPerformed

    private void b23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b23ActionPerformed
        //verifica acima
        if (b22.getText().isEmpty()) {
            b22.setText(b23.getText());
            b23.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b24.getText().isEmpty()) {
            b24.setText(b23.getText());
            b23.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b13.getText().isEmpty()) {
            b13.setText(b23.getText());
            b23.setText("");
            movimentos++;
        }
        //verifica direia
        if (b33.getText().isEmpty()) {
            b33.setText(b23.getText());
            b23.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b23ActionPerformed

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        //verifica acima
        if (b32.getText().isEmpty()) {
            b32.setText(b33.getText());
            b33.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b34.getText().isEmpty()) {
            b34.setText(b33.getText());
            b33.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b23.getText().isEmpty()) {
            b23.setText(b33.getText());
            b33.setText("");
            movimentos++;
        }
        //verifica direia
        if (b43.getText().isEmpty()) {
            b43.setText(b33.getText());
            b33.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b33ActionPerformed

    private void b43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b43ActionPerformed
        //verifica acima
        if (b42.getText().isEmpty()) {
            b42.setText(b43.getText());
            b43.setText("");
            movimentos++;
        }
        //verifica abaixo
        if (b44.getText().isEmpty()) {
            b44.setText(b43.getText());
            b43.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b33.getText().isEmpty()) {
            b33.setText(b43.getText());
            b43.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b43ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        //verifica acima
        if (b13.getText().isEmpty()) {
            b13.setText(b14.getText());
            b14.setText("");
            movimentos++;
        }
        //verifica direia
        if (b24.getText().isEmpty()) {
            b24.setText(b14.getText());
            b14.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b14ActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        //verifica acima
        if (b23.getText().isEmpty()) {
            b23.setText(b24.getText());
            b24.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b14.getText().isEmpty()) {
            b14.setText(b24.getText());
            b24.setText("");
            movimentos++;
        }
        //verifica direia
        if (b34.getText().isEmpty()) {
            b34.setText(b24.getText());
            b24.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b24ActionPerformed

    private void b34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b34ActionPerformed
        //verifica acima
        if (b33.getText().isEmpty()) {
            b33.setText(b34.getText());
            b34.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b24.getText().isEmpty()) {
            b24.setText(b34.getText());
            b34.setText("");
            movimentos++;
        }
        //verifica direia
        if (b44.getText().isEmpty()) {
            b44.setText(b34.getText());
            b34.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b34ActionPerformed

    private void b44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b44ActionPerformed
        //verifica acima
        if (b43.getText().isEmpty()) {
            b43.setText(b44.getText());
            b44.setText("");
            movimentos++;
        }
        //verifica esquerda
        if (b34.getText().isEmpty()) {
            b34.setText(b44.getText());
            b44.setText("");
            movimentos++;
        }
        //define o texto dos movimentos
        lMovimento.setText("Movimentos: " + movimentos);

    }//GEN-LAST:event_b44ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quebracabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quebracabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quebracabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quebracabeca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quebracabeca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lMovimento;
    // End of variables declaration//GEN-END:variables
}
